//
//  OpenRenderBoxShims.h
//  OpenRenderBoxShims

#pragma once

#include <RenderBox/RBPath.h>
#include <RenderBox/RBPathCallbacks.h>
#include <RenderBox/RBPathStorage.h>

typedef RBPath ORBPath;
typedef RBPathElement ORBPathElement;
typedef RBPathRoundedCornerStyle ORBPathRoundedCornerStyle;
typedef RBPathApplyCallback ORBPathApplyCallback;
typedef RBPathCallbacks ORBPathCallbacks;
typedef RBPathCallbacksFlags ORBPathCallbacksFlags;
typedef RBPathCallbacksExtended ORBPathCallbacksExtended;
typedef RBPathStorageRef ORBPathStorageRef;

#define ORBPathElementMoveToPoint RBPathElementMoveToPoint
#define ORBPathElementAddLineToPoint RBPathElementAddLineToPoint
#define ORBPathElementAddQuadCurveToPoint RBPathElementAddQuadCurveToPoint
#define ORBPathElementAddCurveToPoint RBPathElementAddCurveToPoint
#define ORBPathElementCloseSubpath RBPathElementCloseSubpath
#define ORBPathElementRect RBPathElementRect
#define ORBPathElementRoundedRect RBPathElementRoundedRect
#define ORBPathElementFixedRoundedRectCircular RBPathElementFixedRoundedRectCircular
#define ORBPathElementFixedRoundedRectContinuous RBPathElementFixedRoundedRectContinuous
#define ORBPathElementInvalid RBPathElementInvalid

#define ORBPathRoundedCornerStyleCircular RBPathRoundedCornerStyleCircular
#define ORBPathRoundedCornerStyleContinuous RBPathRoundedCornerStyleContinuous

#define ORBPathEmpty RBPathEmpty
#define ORBPathNull RBPathNull
#define ORBPathRetain RBPathRetain
#define ORBPathRelease RBPathRelease
#define ORBPathMakeWithCGPath RBPathMakeWithCGPath
#define ORBPathMakeRect RBPathMakeRect
#define ORBPathMakeEllipse RBPathMakeEllipse
#define ORBPathMakeRoundedRect RBPathMakeRoundedRect
#define ORBPathMakeUnevenRoundedRect RBPathMakeUnevenRoundedRect
#define ORBPathIsEmpty RBPathIsEmpty
#define ORBPathApplyElements RBPathApplyElements
#define ORBPathEqualToPath RBPathEqualToPath
#define ORBPathCopyCGPath RBPathCopyCGPath
#define ORBPathContainsPoint RBPathContainsPoint
#define ORBPathContainsPoints RBPathContainsPoints

#define ORBPathCGPathCallbacks RBPathCGPathCallbacks
#define ORBPathStorageInit RBPathStorageInit
#define ORBPathStorageDestroy RBPathStorageDestroy
#define ORBPathStorageClear RBPathStorageClear
#define ORBPathStorageAppendElement RBPathStorageAppendElement
#define ORBPathStorageAppendPath RBPathStorageAppendPath
#define ORBPathStorageApplyElements RBPathStorageApplyElements
#define ORBPathStorageIsEmpty RBPathStorageIsEmpty
#define ORBPathStorageEqualToStorage RBPathStorageEqualToStorage
#define ORBPathStorageIsSingleElement RBPathStorageIsSingleElement
#define ORBPathStorageGetBezierOrder RBPathStorageGetBezierOrder
#define ORBPathStorageGetBoundingRect RBPathStorageGetBoundingRect
#define ORBPathStorageGetCGPath RBPathStorageGetCGPath
